config/routes.rb
Rails.application.routes.draw do
  get '/jobs/status', to: 'upload_jobs#status'

  get '/login', to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
	get 'slack_oauth', to: 'sessions#slack_oauth'
  get 'slack/oauth/callback', to: 'sessions#slack_oauth_callback'
	post '/slack/upload', to: 'uploads#create'

  get 'welcome/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  root 'welcome#home'

  require 'sidekiq/web'
	mount Sidekiq::Web, at: "/sidekiq"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    if logged_in? && is_slack_linked?
      @slack_channel_list = send_channel_request
      @status_check_job_id = session[:status_check_job_id]
      session[:status_check_job_id] = nil
    end

  end

  private

  # Request (GET )
  def send_channel_request
    uri = URI("#{EasySettings.slack.channel_list_url}?token=#{User.slack_token_decrypt(current_user.slack_access_token)}")

    # Create client
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER

    # Create Request
    req =  Net::HTTP::Get.new(uri)

    # Fetch Request
    res = http.request(req)
    puts "Response HTTP Status Code: #{res.code}"
    puts "Response HTTP Response Body: #{res.body}"
    json = JSON.parse(res.body)
    if json['ok'] == true
      return json['channels'].map { |c| SlackChannel.new(c) }
    end

  rescue StandardError => e
    puts "HTTP Request failed (#{e.message})"
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<div class="signup_area">
    <h1>Slackに画像をアップロードしよう！</h1>

    <% if !logged_in? %>
    <%= link_to 'サインアップ', signup_path, class: 'signup_link' %>
    <% else %>
        <% if is_slack_linked? %>
            <%= form_for(:upload, url: slack_upload_path, html: { id: 'upload_form' }) do |f| %>          
                <div class="photo_preview_area">
                    <div id="photo_preview">
                        <div class="photo_preview_text">Drag&Drop</div>
                        <div>
                            <label for="photo_select">
                                または、ファイルを選択
                                <%= f.file_field :photo, id: 'photo_select', accept: 'image/png,image/jpegpara' %>
                            </label>
                        </div>
                        <div class="photo_preview_img">
                            <div class="photo_preview_img_container">
                                <img src="" alt="" id="photo_preview_img_data">
                                <span id="photo_preview_img_close"></span>
                            </div>
                        </div>
                    </div>
               </div>
                <%= f.hidden_field :drop_photo, value: '', id: 'hidden_drop_photo' %>
                <div id="slack_channel_area">
                    <% if @slack_channel_list&.any? %>
                        <%= f.select :slack_channel_id, options_from_collection_for_select(@slack_channel_list, 'id', 'name') %>
                    <% end %>
                </div>
                <%= f.submit 'Upload', class: 'upload_button' %>
            <% end %>
        <% else %>
            <%= link_to 'Slack連携', slack_oauth_path, class: 'signup_link' %>
        <% end %>
    <% end %>
</div>